### ISSUE TITLE
System.NotSupportedException: 'Unable to determine the provider name for provider factory of type 'System.Data.SqlClient.SqlClientFactory'. Make sure that the ADO.NET provider is installed or registered in the application config

### ISSUE THREAD

**Issue by maddy027** [tonysneed/Demo.AspNetCore2.EF6#1]
Hi , I have created sample app: https://github.com/maddy027/IssueWithEF6WithCore.git 
and getting the below error  
System.NotSupportedException: 'Unable to determine the provider name for provider factory of type 'System.Data.SqlClient.SqlClientFactory'. Make sure that the ADO.NET provider is installed or registered in the application config

VS: 2017 15.8 
EF : 6.2 

Is there anything I am missing here ?.

**Comment by tonysneed** [comment]
Thanks for your sample repo .. I will have a look at it and reply here.

**Comment by furqansafdar** [comment]
Facing the same issue, any clue how to solve or workaround?

**Comment by tonysneed** [comment]
@maddy027 @furqansafdar The reason for this error is that the target framework in your web app needs to be changed from `netcoreapp2.2` to `net461` or later.  Edit the web project csproj file as follows:

```xml
<PropertyGroup>
  <TargetFramework>net461</TargetFramework>
</PropertyGroup>
```

The hard part is that, after making this change, you need to replace the `Microsoft.AspNetCore.App` package reference with individual package references.

```xml
<ItemGroup>
  <PackageReference Include="Microsoft.AspNetCore" Version="2.2.0" />
  <PackageReference Include="Microsoft.AspNetCore.CookiePolicy" Version="2.2.0" />
  <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
  <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" PrivateAssets="All" />
  <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.2.0" />
</ItemGroup>
```

See my [PR](https://github.com/maddy027/IssueWithEF6WithCore/pull/2) for an example.

**Comment by tonysneed** [comment]
Re-open if this does not resolve the issue.

**Comment by maddy027** [comment]
@tonysneed  Thank you for the update.
